version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      - choco install -y yarn
  build:
    commands:
      - yarn
      - yarn package --win
