version: 0.2

phases:
  build:
    commands:
      - Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      - choco install -y yarn
      - refreshenv
      - yarn
      - yarn package --win
