version: 2.1
description: test macOS and win32 builds in circeci

orbs:
  win: circleci/windows@1.0.0

jobs:
  build_macos:
    description: Test macOS build
    macos:
      xcode: '11.0.0'
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
      - run:
          name: Run macOS build
          command: |
            yarn
            yarn package --mac

  build_win32:
    description: Test win32 build
    executor: win/vs2019
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: |
            Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
            choco install yarn
      - run:
          name: Run win32 build
          command: |
            yarn
            yarn package --win

workflows:
  macos-test-pipeline:
    jobs:
      - build_macos
  win32-test-pipeline:
    jobs:
      - build_win32
